[package]
name = "sample_module"
version = "0.1.0"
authors = ["Matti Astrand <mattiastr@gmail.com>"]
edition = "2018"

[dependencies]
pyo3 = { version = "0.12", features = ["extension-module"]}
numpy = "0.12"
ndarray = "0.14"
rand = "0.7"
rayon = "1.5"

[lib]
name = "sample_module"
crate-type = ["cdylib"]
