import numpy as np

def add5(x: int) -> int: ...
def cumsum_inplace(x: np.ndarray): ...
def ev_presses(x: float, n: int) -> float: ...

class Juttu:
    def __init__(self, x: int, y: bool): ...
    def xsq(self) -> int: ...
    @property
    def is_juttu(self) -> bool: ...

